### ISSUE TITLE
Support stream - Media entities, an stream properties

### ISSUE THREAD

**Issue by congysu** [OData/RESTier#173]
Media entities, an stream properties:
[11.4.7 Managing Media Entities](http://docs.oasis-open.org/odata/odata/v4.0/errata02/os/complete/part1-protocol/odata-v4.0-errata02-os-part1-protocol-complete.html#_Toc406398336)
[11.4.8 Managing Stream Properties](http://docs.oasis-open.org/odata/odata/v4.0/errata02/os/complete/part1-protocol/odata-v4.0-errata02-os-part1-protocol-complete.html#_Toc406398340)

Related issues: https://github.com/OData/WebApi/issues/24 https://github.com/OData/WebApi/issues/149
https://github.com/OData/WebApi/issues/328

**Comment by ivanko2000** [comment]
+1
Great that it was addressed for https://github.com/OData/WebApi/issues/149, so 'manual' option is available. But would be even better if implemented in 'turn-key' fashion in RESTier...

**Comment by ivanko2000** [comment]
I tried following the existing content in the issue reports on this topic to implement this in my RESTier project, but failed miserably... Just wondering if there is any chance this has been resolved or if there is an example I could study?

**Comment by chinadragon0515** [comment]
@ivanko2000 RESTIer has not supported it yet, we will investigate this item and evaluate effort needed. I have as customer ask label to increase the priority, thanks.

**Comment by ivanko2000** [comment]
@chinadragon0515, since you were asking about requests/suggestions, I would ask to prioritize this feature for GA, especially e.g. with #301 already in place. I am faced with binary content properties in my project, and it's still much more complicated to deal with them than it should be. Thank you for your efforts!

**Comment by raffaeu** [comment]
Guys we are working with OData v 4.0 and it has been more than 1 year now. Now we are completely stuck, we follow the instructions over this post on MSDN:
https://blogs.msdn.microsoft.com/mrtechnocal/2013/10/31/media-resource-support-for-odata-in-web-api/#comment-325
which is from **2013** and now **July 2016** we realize that this method is still now available?

`IEdmModel.SetHasDefaultStream
`
which is mandatory for us in order to provide a link from the OData entity to the real content (stream) of the entity.
What are we supposed to do now? Rollback everything to V 3.0 and loose months of work or did you release a fix for this bug?

**Comment by chinadragon0515** [comment]
@raffaeu sorry to hear this blocks you, can I know which library you are using now? RESTier or Web Api OData? I see you also add comments to Web Api OData.

For restier, it is only for v4 and now is 0.5 release, and 0.6 release is planned.
I have marked it as customer ask which means high priority, it is in top of my list. I will work closely with Web Api OData peer to see what's the workaround now and what restier can improve the support.

**Comment by raffaeu** [comment]
Yes, we are working with Microsoft Asp.Net Web Api Odata version 4.0, and
their message board redirect to this backlog. For us even a workaround that
allows me to have MLE link in my entity will be acceptable.

**Comment by chinadragon0515** [comment]
OK, I see, then you will need to monitor status for issue in this repository, https://github.com/OData/WebApi/issues

This repository is for restier, and this issue is still in top list of restier.

**Comment by raffaeu** [comment]
All right, I understand.
Thank you for the reply. If there is anything I can do for help, I'll be
happy to.

**Comment by chinadragon0515** [comment]
@raffaeu I did some check on the media type support today,  I have some questions for you,
1. You need to build a model who is Media entity (HasStream is true), can I know how you build model? Build with EDM or ODataConversionModel builder, refer to http://odata.github.io/WebApi/#02-01-model-builder-abstract for detail on different way for model builder.

2. If you are using ODataConversionModelBuilder, it is already support to set such flag, refer to https://github.com/OData/WebApi/pull/379 and http://odata.github.io/WebApi/#06-04-streamEntity

3. If you are using Edm directly, you can mark an entity has stream via using this constructor "EdmEntityType(string namespaceName, string name, IEdmEntityType baseType, bool isAbstract, bool isOpen, bool hasStream)"

**Comment by ivanko2000** [comment]
Looks like I missed the question somehow... Hopefully someone is still listening:
the use case is having a 'stream property' field in an entity that stores binary content (file); the content is not expected to be returned when querying the entity directly, just a link for separate retrieval/(update) operations. The binary content is expected to map into a binary DB column, e.g. image/varbinary / BLOB

**Comment by raffaeu** [comment]
Hi @chinadragon0515 , sorry but I missed the question too.
In our case we have a Document Management app which contains Files and they are queryable via OData. What I have implemented is a custom Route but it's annoying, the ideal would be to have

http://localhost/odata/v4/Files for query and http://localhost/odata/v4/Files(1235)/$value to get the stream out which should contain also the media-type header.

An example is available here: http://www.odata.org/blog/enhancing-odata-support-for-streams/

**Comment by chinadragon0515** [comment]
Can you refer to this link https://github.com/chinadragon0515/ODataSamples/tree/mediaentity/RESTier/MediaEntitySample to have a preview of the sample we support? Any questions, help to let us know, thanks.

**Comment by raffaeu** [comment]
Hi @chinadragon0515 , I will have a look for sure and let you know if I encounter any problem.
I wasn't aware of this option, good to know.

**Comment by raffaeu** [comment]
@chinadragon0515, sorry for the late answer but it took me a while to have time for this
So, right now we are using the latest packages and I can't get this sample working:
https://github.com/chinadragon0515/ODataSamples/tree/mediaentity/RESTier/MediaEntitySample
Because the namespace Microsoft.OData.Core doesn't exists anymore if we upgrade the Nuget package Microsoft.OData.Core to version 7.0.0.0

So, what is the correct solution, if any, to implement with Web Api a Media Stream using OData 5.7? Because I can't find any sample working anymore after we upgraded to the latest

**Comment by robertmclaws** [comment]
Thanks for your input! We are resetting the project as we move to (finally!) ship 1.0. While we are closing this for now, we will re-address legacy feature requests at a later date. Please be sure to check out the latest nightly builds (and the upcoming 1.0 Beta 2 build) and let us know if you run into any issues. Thanks again!
