### ISSUE TITLE
System.Web.Mvc.AuthorizeAttribute not working in protecting OData.

### ISSUE THREAD

**Issue by jeeshenlee** [OData/RESTier#174]
Seeking AuthorizeAttribute suppport on OData.

Just tried adding a working AuthorizeAttribute on a OData RESTier action and it does not trigger the authorization method. I believe this is a good feature to have since many ASP MVC project has already such logic implemented in the existing project.

Thanks. Good work on RESTier :)

**Comment by chinadragon0515** [comment]
Can I know the reason you need to use System.Web.Mvc.AuthorizeAttribute but not System.Web.Http.Authorize ?

Note Restier is based on ApiController.

And this is from http://stackoverflow.com/questions/19152109/system-web-http-authorize-versus-system-web-mvc-authorize
You must use System.Web.Http.Authorize against an ApiController (Web API controller) and System.Web.Mvc.Authorize against a Controller (MVC controller). Since the framework runs the filters as part of the pipeline processing and the controllers expect the right filter to be applied, if you don't use the corresponding filter, authorization will not work.

**Comment by chinadragon0515** [comment]
Close the issue as System.Web.Http.Authorize should be used for ODataController which is based on ApiController, any more issues, open new issues, thanks.
