### ISSUE TITLE
Add detailed error information for exceptions

### ISSUE THREAD

**Issue by karataliu** [OData/RESTier#24]
In some places the code just throw exception without error message. We'd better add detailed information for those error messages.

**Comment by lewischeng-ms** [comment]
We should unify the exception in RESTier. That is to say if LINQ expression or EF throws an exception. RESTier should wrap it and throw proper exception or return correct status code instead of just leaking the exception to end user.

As an example, #47 shows a duration-related exception thrown by EF. In this case, we should catch it and return 4XX bad request instead of return 500 internal server error. This is a client request problem not service issue.

**Comment by lewischeng-ms** [comment]
Part of the work mentioned is already done by https://github.com/OData/RESTier/commit/ec3dc8aa1ef568cb0d863797d19d4f64831070b0

**Comment by lewischeng-ms** [comment]
Related pull request #243
