### ISSUE TITLE
Add Entity level Convention

### ISSUE THREAD

**Issue by ielbury** [OData/RESTier#260]
I notice that the current convention implementation does not include Entity level validations i.e. IValidatableObject. 

Most applications will require a convention using the IValidatableObject interface to validate an entity and optionally related domain. It does not look like it would be too much work to implement?

**Comment by lewischeng-ms** [comment]
Hi @ielbury , thank you for your advice. RESTier's validation logic mainly includes **query inspectors** and **query filters**. These hooks are invoked on each critical node of a LINQ expression. 

Here is a simple example: say the user requests `~/People(1)/FirstName`, RESTier will build a query expression like `ApiData.Source("People").Where(p => p.Id == 1).Select(p => p.FirstName)`. The critical nodes are:
 - The query source `ApiData.Source("People")` which represents a top-level resource called `People`
 - The lambda parameter `p` which represents each single entity within `People`
 - The property access `p.Id` and `p.FirstName`

By using query inspectors, you can return a bool for each node above to indicate whether the node passes your inspection or validation. An error response will be returned if the validation fails. By using query filters, you can even possibly return a new expression wrapping a node to filter out some entities or some properties that shouldn't be returned.

For example you can add a query inspector to prohibit access to `p.Password` or add a query filter to append a `Where(p => p.Id != 1)` clause to the node `ApiData.Source("People")` to filter out all entities whose `Id` are `1`.

Though all these hooks directly apply to the LINQ expressions rather than the results, I think most of the requirements can be satisfied in various ways. I am not sure if there are additional cases from you where validation must be done after the results are computed. Please let us know.

Thanks.

**Comment by ielbury** [comment]
I think you are missing my point. What I am saying is you need a OnValidate convention with a signature of something like:

```
IEnumerable<ValidationResult> OnValidate(ValidationContext validationContext()
```
Please look at Scott Gu's post http://weblogs.asp.net/scottgu/class-level-model-validation-with-ef-code-first-and-asp-net-mvc-3 on the use of this interface and for a better idea of why.

The bottom line is we need to return ValidationResults for the validation of an entity as well as for validation attributes for an individual property.

**Comment by lewischeng-ms** [comment]
@ielbury Oh, apology for the misunderstanding... I took a look at the post you mentioned and this could be a useful and interesting feature. Thanks:)

Basically what `Restier.EF` needs to do is to provide a way to turn on EF's validation and serialize the result to payload. Futhermore it's better to implement a new convention in `Restier.Core` which enables user to write some method, say `OnValidate` to his `Api` class. For example, user can call `DbContext.GetValidationErrors()` in `Api.OnValidate` to return the `ValidationResult`s of the inner `DbContext`. This convention shall be called before committing the changes (such as added or modified entities) to ensure data consistency. Am I understanding correctly this time?

**Comment by ielbury** [comment]
I think that the results need to be aggregated from DbContext.GetValidationErrors() and Api.OnValidate. This will allow people the implement the IValidatableObject in their Entity OR they implement OnValidate.

My personal opinion would be for Restier's conventions to handle all my business logic and leave the POCO's clean (No IValidatableObject ). The fact that some of the validation is in attributes on properties + in conventions makes this architecture less than ideal but it is what it is. 

To be pragmatic, I think you should look at the Lightswitch conventions as they have been tried and work well.

**Comment by lewischeng-ms** [comment]
@ielbury Okay, got your point. Thanks.

Reference: https://msdn.microsoft.com/en-us/library/ff852065.aspx

**Comment by ielbury** [comment]
Here is an article that more clearly describes the Lightswitch save pipeline which is VERY similar to what you are implementing with Restier http://www.codemag.com/article/1103071 

Thanks,
Ian

**Comment by robertmclaws** [comment]
Thanks for your input! We are resetting the project as we move to (finally!) ship 1.0. While we are closing this for now, we will re-address legacy feature requests at a later date. Please be sure to check out the latest nightly builds (and the upcoming 1.0 Beta 2 build) and let us know if you run into any issues. Thanks again!
