### ISSUE TITLE
Missing 0.4.0-rc Microsoft.Restier.Security nuget package

### ISSUE THREAD

**Issue by strtdusty** [OData/RESTier#262]
I see that a new release for 0.4.0 rc has been made for several of the nuget packages but a corresponding security package was not released.  Was this an oversight or part of a delayed release?

**Comment by lewischeng-ms** [comment]
Hi @strtdusty Sorry that temporarily `Microsoft.Restier.Security` is not part of the release scope because we do not have enough time and resource developing the module and having it fully tested. But we will put effort on it sometime in the future if there is much customer ask. Thanks for your support!

**Comment by gabrielsadaka** [comment]
Hi @lewischeng-ms is there any progress on the `Microsoft.Restier.Security` package release? As we are very happy with Restier however without any security it cannot be used.

**Comment by lewischeng-ms** [comment]
Hi @gabrielsadaka sorry we haven't yet prepared to release `Microsoft.Restier.Security` however since it is just a collection of pluggable hooks to RESTier, you are free to integrate the code of the necessary features into your project and make any customization you want. Thanks.

**Comment by chinadragon0515** [comment]
RESTier will not release component for security, it will depend on WebAPi security mechanism.
If you have any security requirements but WebApi security can not achieve, let us know. thanks.
