### ISSUE TITLE
compilation errors when linking to NuGet package

### ISSUE THREAD

**Issue by lgadola** [OData/RESTier#300]
When I link to the NuGet package, I get errors like:
Error	CS7069	Reference to type 'DomainParticipantAttribute' claims it is defined in 'Microsoft.Restier.Core', but it could not be found	Microsoft.Restier.Samples.Northwind	C:\temp\RESTier-master\src\Microsoft.Restier.Samples.Northwind\Models\NorthwindApi.cs

Error	CS0103	The name 'ApiPermissionType' does not exist in the current context	Microsoft.Restier.Samples.Northwind	C:\temp\RESTier-master\src\Microsoft.Restier.Samples.Northwind\Models\NorthwindApi.cs

tried with Restier.Samples.Northwind, replaced the references to Restier with the nuget package and got the same error as in my own program

**Comment by lewischeng-ms** [comment]
Hi @lgadola , could you please provide which version of Visual Studio (including update) you are using? This looks more like an infrastructure issue.

**Comment by lgadola** [comment]
I am using Version 14.0.24720.00 Update 1

**Comment by lewischeng-ms** [comment]
We have exactly the same Visual Studio version here. But we have never seen this error before. Are you building the solution on a **clean** repository? If not so, please do a `git checkout -f`, reopen VS with the solution and try again. If you still see that error, please provide detailed environment information so that we can try to repro your problem.

**Comment by lgadola** [comment]
Did you replace the project references with the nuget packages?
I stumbled across the error when trying to run my own implementation of a restier service. I installed the 4 nuget packages and got the error.
I then downloaded the whole restier solution, opened Microsoft.Restier.Samples.Northwind, deleted the references to Microsoft.Restier.Core, ..EntityFramework, ..Security, ..WebApi and then installed all these packages from Nuget. I got exactly the same error then.

**Comment by lewischeng-ms** [comment]
Hi @lgadola , I know your problem. This is because `Microsoft.Restier.Samples.Northwind` also takes a dependency on `Microsoft.Restier.Security`. However the security module for 0.4.0 has not been released so far. Thus you need to replace the reference to `Microsoft.Restier.Core` of this project with NuGet as well. But we are doing some breaking changes in `Microsoft.Restier.Core` which makes the current `Microsoft.Restier.Security` source incompatible with the NuGet version of `Microsoft.Restier.Core`. That's why you can't build the project anyway.

If you are looking for a modern sample service for RESTier, please use the Trippin service instead (https://github.com/OData/RESTier/tree/master/test/ODataEndToEndTests/Microsoft.Restier.WebApi.Test.Services.Trippin). The Northwind service is very ancient and has been deprecated (just for regression-test purpose) by now.

Thanks.

**Comment by lgadola** [comment]
Thanks, Lewis. I will look into that, then
