### ISSUE TITLE
release 0.6 [Done]

### ISSUE THREAD

**Issue by chinadragon0515** [OData/RESTier#481]
Track effort to release 0.6 version,
1. public api review
2. update document
3. build signed dll and validation
4. update samples to new version with local dll
5. upload dll to nuget
6. final check on update dll with new service with online dll
7. make updated document live
8. announce the new release (odata discussion, msdn blog.....)
9. add tag to existing code

**Comment by chinadragon0515** [comment]
A preview of items to be release, http://odata.github.io/RESTier/v0.6/#06-08-0-6-0

**Comment by VladlenBulatov** [comment]
Please add ability to allow users correctly using .Ignore() and other customizations while model building (like in EF)
Simple add line to ApiBase.cs -
         `public Action<ODataConventionModelBuilder> OnModelCreating { get; set; }`
And two lines to RestierModelBuilder.cs -
```
           if (api.OnModelCreating != null)
               api.OnModelCreating(builder);
```
before line with  `var model = (EdmModel)builder.GetEdmModel();`

**Comment by moander** [comment]
Great news! :) 

Is it possible for RESTier to start using https://www.myget.org/gallery/odlnightly or something to push updates more frequently?

**Comment by chinadragon0515** [comment]
@VladlenBulatov For extend model part, we will do with #457, we have worked with Web Api odata team on this part , and it is planned as part of next release, you can refer to https://github.com/chinadragon0515/RESTier/commit/b9bc50b1059181aee65229c081d84dbc7873b9aa to have a preview on what we plan to do.
Now in restier, only part of model build is using ODataConversionModelBuilder, and with new design, restier will fully adopt ODataConversionModelBuilder.

Let me know whether the new model extend mechanism meet your request.

**Comment by chinadragon0515** [comment]
@moander Considering the consumer base we have now, we have not enabled nightly build yet, we plan to enable after first GA which is planned 4Q this year, before that time, if you need any special build, help to let me know, I can temp push build for you.

**Comment by chinadragon0515** [comment]
Next release is planned in 4Q2016, anyone has any request/comments/suggestions, let us know, we always consider consumers request as high priority items

**Comment by moander** [comment]
@chinadragon0515: I've been doing some research on how to implement a "database only" feature in RESTier but that has proven to be more difficult than first thought.

OData is a great way to expose a database, and a database server is a great place to store database schemas, so I thought it would be a good idea to be able to expose it directly without adding an extra layer of manual labor maintaining POCO classes.

So my feature request is something like this :)

```
services.AddService<IModelBuilder>(new ModelBuilder("Data Source=server; Initial Catalog=DatabaseToExpose"));
```

**Comment by chinadragon0515** [comment]
@moander  so you mean you will not have CLR class like a Person class which is for Person table in database? Then you want the model is built from database schema. And then for query,  the LINQ expression build will depend of database schema?

For model builder, you can do anything you want, but we have not tried that way,  you will need to get the schema and use Edm model builder directly http://odata.github.io/WebApi/#02-02-model-builder-untyped

Even we have model builder as the query and change depends on entity framework, then it still need effort to make that part work.

Can I know the reason we need this? Can we code first from database to generate the DbContext class and POCO class?

**Comment by moander** [comment]
@chinadragon0515: What I'm trying to do is to expose a database as-is using only a connection string.

I was able to do it, but the solution was way to dirty to consider for production ;)

* Extracting csdl/ssdl/msl from a connection string was straight forward using the built-in EntityStoreSchemaGenerator. 

* Loading the schema into a DbContext was also straight forward using the `metadata=..` parameter in the EF connection string. 

Then you could (not that anyone should;) do a `new System.Data.Entity.DbContext("...")` directly without even requiring a ` class MyDbContext : DbContext`.

Running queries against the context will fail because it can't find any CLR objects backing it's schema. And I did not find any built-in stuff that could make them for me either, so from here the work-around get's really ugly.

* The default T4 templates does not support pre-processing so I had to embed the whole thing, output them to disk at runtime, run the T4 transformer using the EDMX generated in the first step, read back the outputted files and compile them using the CSharpCompilation class.

* Expose the DB using Restier

This is a lot of work when all you want to do is to expose a DB using OData ;)

**Comment by chinadragon0515** [comment]
@moander our design is always need a CLR class now, and when we get the data from database, we depends on provider to constructor a CLR class, then OData code will convert it to a odata entity object, if without CLR class, there is lots of work to do now. I am afraid we have bandwidth to support such scenario now.

In the meanwhile, RESTier does not support dynamic model now, we have issue https://github.com/OData/RESTier/issues/493 to track dynamic model support.

We are welcome contribution, if you can work out design or send us a pull request, that will be great.

**Comment by chinadragon0515** [comment]
I opened https://github.com/OData/RESTier/issues/494 to track your request as this issue is done.
