### ISSUE TITLE
release 1.0 (First GA, 1.0.0-beta is released.)

### ISSUE THREAD

**Issue by chinadragon0515** [OData/RESTier#503]
Track effort to release 1.0 version, this is first GA version based on ODL 7.x and WAO 6.x,
1. public api review [Done for beta]
2. update document [Done for beta]
3. build signed dll and validation [Done for beta]
   Some GA process like QE process, threat model and so on [Ongoing]
4. update samples to new version with local dll  [Done for beta]
5. upload dll to nuget [Done for beta]
6. final check on update dll with new service with online dll [Done for beta]
7. make updated document live [Done for beta]
8. announce the new release (odata discussion, msdn blog.....)
9. add tag to existing code [Done for beta]

**Comment by chinadragon0515** [comment]
A preview of release content http://chinadragon0515.github.io/RESTier/v1.0/#06-09-1-0-0

**Comment by robertmclaws** [comment]
Is there any chance of changing the DI between now and the V1 release to behave *exactly* like ASP.NET Core 1.0 does, since you're using Core 1.0's DI? AFAIK passing an IServiceCollection into your class is not the right way to do it... people wanting to change behavior should be making those changes in Startup.cs at app launch and registering those items with the context themselves.

**Comment by chinadragon0515** [comment]
Can you help to elaborate the issue you have? In restier, we did not expose interface for user to  create container now. We expose interface for user to add service to the container.

Can I know what kinds of behavior wants to change? If I know more detail, we can evaluate the possible changes and see whether we should add such changes into 1.0 release.

**Comment by cilerler** [comment]
I'm confused 😕 I thought **.NET CORE** support will be there for **v1**, what happened?
It looks like [issue](https://github.com/OData/RESTier/issues/464) is there but still no progress?  Any idea when it will be available?

**Comment by mikepizzo** [comment]
@cilerler: .NET Core support in RESTier relies on .NET Core support in WebAPI OData -- which is not a trivial ask, due to changes in the WebAPI framework.  But it is a high priority work item for us that we are actively working on.

**Comment by Compufreak345** [comment]
@robertmclaws @mikepizzo Can you give an update on .Net Core-support? If I understand it correctly there is some kind of alpha available for WebAPI OData for .Net Core and you started looking into it?
https://github.com/OData/WebApi/issues/939#issuecomment-353742262

Thanks & best regards,
Christoph

**Comment by robertmclaws** [comment]
@Tiberriver256 @Compufreak345 @cilerler WebApi OData is now running on .NET Core. As soon as we have Restier on Classic ASP.NET stabilized, we'll start working on ASP.NET Core support. In the meantime, I will be publishing some guidance soon on how to use Restier in scalable API development. If you do it right, you can still have ASP.NET Core apps talking to a Restier-powered Classic ASP.NET API and not be blocked by the progress of the project.

I'm going to close this issue for now, since it was originally-focused on communication about the first Beta release. But feel free to continue discussing the stuff I just mentioned.
