### ISSUE TITLE
OnInserting / OnUpdating 500 Error When Changing Properties on the Entity

### ISSUE THREAD

**Issue by peder** [OData/RESTier#533]
### Assemblies affected

RESTier 0.6.0
### Reproduce steps

Any time I change a property on an object in OnInserting or OnUpdating, RESTier throws a 500 error without any details. Additionally, `Global.asax` `Application_Error` method doesn't fire, so I have no exception details to share.

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Microsoft.Restier.Providers.EntityFramework;
using System.Security.Principal;

namespace Ecm.Api.Models
{
    public class EcmApi : Microsoft.Restier.Providers.EntityFramework.EntityFrameworkApi<EcmContext>
    {
        protected void OnInsertingSearches(Search search)
        {
            this.onInsertingEntityBase(search);
        }

        protected void OnUpdatingSearches(Search search)
        {
            this.onUpdatingEntityBase(search);
        }


        private void onInsertingEntityBase(EntityBase entityBase)
        {
            var userName = WindowsIdentity.GetCurrent().Name;
            this.onInsertingEntityBase(entityBase, userName);
        }

        private void onInsertingEntityBase(EntityBase entityBase, String userName)
        {
            entityBase.CreatedBy = userName;
            entityBase.CreatedDate = DateTime.Now;

            this.onUpdatingEntityBase(entityBase, userName);
        }

        private void onUpdatingEntityBase(EntityBase entityBase)
        {
            var userName = WindowsIdentity.GetCurrent().Name;
            this.onUpdatingEntityBase(entityBase, userName);
        }

        private void onUpdatingEntityBase(EntityBase entityBase, String userName)
        {
            entityBase.ModifiedBy = userName;
            entityBase.ModifiedDate = DateTime.Now;
        }
    }
}
```
### Expected result

I would expect that I can modify an entity on insert or update to set auditing field values.
### Actual result

500 Internal Server Error
### Additional details

Can we modify an entity on insert/update? Is this an error simply because I'm using inheritance with my entities?

**Comment by mikepizzo** [comment]
Thanks for the follow-up @peder. Sounds like we should clarify this in the docs.

**Comment by robertmclaws** [comment]
So, I think this is going to be a very common pattern... updating audit properties on submit. We're doing it in about 9 RESTier APIs now and have not encountered this problem. It might have something to do with the data time in your underlying EF model. We've standardized on DateTimeOffset(7) as the underlying store, and updating with DateTimeOffset.Now.

Either way, I believe this is not a RESTier-specific issue. However, I will say that in your WebApi configuration code (the same place where you call `config.Filter().Expand().Select().OrderBy().MaxTop(100).Count()`), make sure you call `config.SetTimeZoneInfo(TimeZoneInfo.Utc);` so that everything lines up properly with how you're getting DateTime info.

HTH!
