### ISSUE TITLE
Restier not custom Controllers

### ISSUE THREAD

**Issue by thechadc** [OData/RESTier#535]
I'm having some difficulty trying to add custom controller to be included in restiers routing.

I've followed these guides:
http://odata.github.io/RESTier/#03-02-Controllers
http://restier.readthedocs.io/en/latest/extending-restier/additional-operations/

The error received is that "The path template 'ResetDataSource' on the action 'ResetDataSource' in controller 'TrippinController' is not a valid OData path template. Resource not found for the segment 'ResetDataSource'".

![image](https://cloud.githubusercontent.com/assets/1702383/19961257/47ca243a-a1ba-11e6-8f34-969874673b41.png)

Does the custom controllers need to be registered in the routing? my understanding was that restiers adds these custom controllers(odata/api). 

Am I missing something ?

**Comment by iqmeta** [comment]
Maybe realated... since update to 1.0.0 and OData 6 nuget...

Composite Route always ends up in default Get()

![image](https://cloud.githubusercontent.com/assets/7533842/19972411/46290f6a-a1e2-11e6-9c6e-04119b452927.png)

CompositeKeys ODataControler based on 

https://github.com/OData/ODataSamples/tree/master/WebApi/v4/ODataCompositeKeySample/ODataCompositeKeySample

Hint: CompositeKeyRoutingConvention : EntityRoutingConvention
with Restier and new Odata
=> override string SelectController
=> override string SelectAction
calls are gone.

**Comment by thechadc** [comment]
@iqmeta Looking at the OData sample code, it seems it's just the documentation that doesn't explain how it should be implemented, got it working based on the OData sample

**Comment by iqmeta** [comment]
@thechadc right, not the same more like some changes in OData
https://github.com/OData/ODataSamples/issues/51
