### ISSUE TITLE
Reference issue in WebApiRoute Config while using Restier

### ISSUE THREAD

**Issue by suchithnair** [OData/RESTier#582]
I ran into this issue with MapRestierRoute configuration in the web API Config.
![image](https://user-images.githubusercontent.com/7897093/27974440-096dae08-632c-11e7-8919-00b1b4dbda58.png)

Followed the link from the documentation that was provided

http://odata.github.io/RESTier/#01-01-Introduction

Currently stuck at the step with setting Web API Route config for Restier. 

![image](https://user-images.githubusercontent.com/7897093/27974513-3ca0cfee-632c-11e7-866d-1c8186ac79fd.png)

Seems like one of the libraries that got installed has some issues.

Appreciate any help in this regard.

**Comment by Spragalas** [comment]
Hi,

MapRestierRoute is an extansion method which is located at: Microsoft.Restier.Publishers.OData namespace. You should be good to go after you add an using.

**Comment by robertmclaws** [comment]
Hello! @Spragalas is correct, that should have solved the problem. Since there has been no response on this issue, I'm going to go ahead and close it. We're going to be putting out a new Beta soon. If you're still having problems after upgrading to the latest version, please re-open the issue. Thanks!
