### ISSUE TITLE
improve empty result

### ISSUE THREAD

**Issue by mojobec** [OData/RESTier#626]
if a query returns nothing RESTier will query again without the filters to know if it should return a 404 or empty result set.
the result is that empty requests take longer than ones that return data.

**Comment by robertmclaws** [comment]
Hmmm, yeah there probably needs to be a better way to do that. Can you point out where the code does that so that I can take a look? Maybe we can get a quick fix in for this.

Thanks!

**Comment by mojobec** [comment]
[DefaultQueryHandler line 84](https://github.com/OData/RESTier/blob/45f858d8cb62f0c0d854b5cfdca61601f4cea409/src/Microsoft.Restier.Core/Query/DefaultQueryHandler.cs#L84)

**Comment by robertmclaws** [comment]
Great news! This has been fixed in the latest nightly builds, and will make it into the upcoming 1.0 Beta 2 release. Thanks for finding where it was a problem in the code, so I could fix it quickly. You can grab a build from our nightly feed in about 20 minutes. Please check it and make sure it works as desired, and re-open if there are any issues. Thanks so much for helping to make the product better!
