### ISSUE TITLE
Support DB first

### ISSUE THREAD

**Issue by Razgort** [OData/RESTier#636]
Hello guys,

I would like to know if your solution is viable / suits a db first approach with entity core and asp core 2.2. And what are your plans for asp core 3 ?

Thanks in advance

**Comment by robertmclaws** [comment]
It absolutely supports Database-First, I'm using it in multiple production applications that generate the DbContext using EDMX files. Honestly, it's my preferred approach, because I'm not a fan of EFMigrations.

Now, we are not able to support EF Core or ASP.NET Core yet, but it is our intention to start working on that as soon as we get the version that has been in progress for the last 5 years out the door ;). We should be ready to start talking about that in May.

Hoping to show off a Database-First implementation in next week's Community Standup... check us out Tuesday March 5th at 12PM EST at http://bit.ly/RESTierYouTube

**Comment by Razgort** [comment]
this is great news man !! thanks
