### ISSUE TITLE
RESTier fails non-nullable DateTime

### ISSUE THREAD

**Issue by karataliu** [OData/RESTier#74]
When database schema contains non-null DateTime type, the update request would fail. Also DateTime property doesn't appear in metadata.

**Comment by rob3c** [comment]
RESTier only supports OData v4.0, and v4 dropped support for the DateTime primitive type in favor of DateTimeOffset. Unfortunately, the $metadata generator simply ignores DateTime properties because they're no longer in the spec (even though many are still using them), and you only find out about it via runtime errors.

Cheers,
Robert

**Comment by karataliu** [comment]
Use #103 for tracking

**Comment by Vaccano** [comment]
So sad.  DateTime is used so much more than DateTimeOffset.  This limits the users of this to a very small subset just to deprecate a well known datatype.
